name: Develop Site CI/CD

on:
  push:
    branches:
      - develop

jobs:
   deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Build Angular App
      run: npm run develop

    - name: Deploy to S3
      if: success()
      run: aws s3 sync ./dist/develop s3://dev-finally-webresponsive

    - name: Invalidar CloudFront
      if: success()
      run: aws cloudfront create-invalidation --distribution-id E2XNSGJMKY6KD4 --paths "/*"

    - name: Sonarqube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
